/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettlementRouteImport } from './routes/_authenticated/settlement'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBacktestRouteImport } from './routes/_authenticated/backtest'
import { Route as ApiPublicV1SharpMovesRouteImport } from './routes/api/public/v1/sharp-moves'
import { Route as ApiPublicV1PredictionsRouteImport } from './routes/api/public/v1/predictions'
import { Route as ApiPublicV1PicksRouteImport } from './routes/api/public/v1/picks'
import { Route as ApiPublicCronRefreshRouteImport } from './routes/api/public/cron/refresh'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettlementRoute = AuthenticatedSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacktestRoute = AuthenticatedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicV1SharpMovesRoute = ApiPublicV1SharpMovesRouteImport.update({
  id: '/api/public/v1/sharp-moves',
  path: '/api/public/v1/sharp-moves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PredictionsRoute = ApiPublicV1PredictionsRouteImport.update({
  id: '/api/public/v1/predictions',
  path: '/api/public/v1/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PicksRoute = ApiPublicV1PicksRouteImport.update({
  id: '/api/public/v1/picks',
  path: '/api/public/v1/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshRoute = ApiPublicCronRefreshRouteImport.update({
  id: '/api/public/cron/refresh',
  path: '/api/public/cron/refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/live': typeof AuthenticatedLiveRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settlement': typeof AuthenticatedSettlementRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/api/public/v1/picks': typeof ApiPublicV1PicksRoute
  '/api/public/v1/predictions': typeof ApiPublicV1PredictionsRoute
  '/api/public/v1/sharp-moves': typeof ApiPublicV1SharpMovesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/live': typeof AuthenticatedLiveRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settlement': typeof AuthenticatedSettlementRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/api/public/v1/picks': typeof ApiPublicV1PicksRoute
  '/api/public/v1/predictions': typeof ApiPublicV1PredictionsRoute
  '/api/public/v1/sharp-moves': typeof ApiPublicV1SharpMovesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/backtest': typeof AuthenticatedBacktestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/settlement': typeof AuthenticatedSettlementRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/api/public/v1/picks': typeof ApiPublicV1PicksRoute
  '/api/public/v1/predictions': typeof ApiPublicV1PredictionsRoute
  '/api/public/v1/sharp-moves': typeof ApiPublicV1SharpMovesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/backtest'
    | '/dashboard'
    | '/live'
    | '/settings'
    | '/settlement'
    | '/api/public/cron/refresh'
    | '/api/public/v1/picks'
    | '/api/public/v1/predictions'
    | '/api/public/v1/sharp-moves'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/backtest'
    | '/dashboard'
    | '/live'
    | '/settings'
    | '/settlement'
    | '/api/public/cron/refresh'
    | '/api/public/v1/picks'
    | '/api/public/v1/predictions'
    | '/api/public/v1/sharp-moves'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/backtest'
    | '/_authenticated/dashboard'
    | '/_authenticated/live'
    | '/_authenticated/settings'
    | '/_authenticated/settlement'
    | '/api/public/cron/refresh'
    | '/api/public/v1/picks'
    | '/api/public/v1/predictions'
    | '/api/public/v1/sharp-moves'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicCronRefreshRoute: typeof ApiPublicCronRefreshRoute
  ApiPublicV1PicksRoute: typeof ApiPublicV1PicksRoute
  ApiPublicV1PredictionsRoute: typeof ApiPublicV1PredictionsRoute
  ApiPublicV1SharpMovesRoute: typeof ApiPublicV1SharpMovesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settlement': {
      id: '/_authenticated/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof AuthenticatedSettlementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtest': {
      id: '/_authenticated/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthenticatedBacktestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/v1/sharp-moves': {
      id: '/api/public/v1/sharp-moves'
      path: '/api/public/v1/sharp-moves'
      fullPath: '/api/public/v1/sharp-moves'
      preLoaderRoute: typeof ApiPublicV1SharpMovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/predictions': {
      id: '/api/public/v1/predictions'
      path: '/api/public/v1/predictions'
      fullPath: '/api/public/v1/predictions'
      preLoaderRoute: typeof ApiPublicV1PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/picks': {
      id: '/api/public/v1/picks'
      path: '/api/public/v1/picks'
      fullPath: '/api/public/v1/picks'
      preLoaderRoute: typeof ApiPublicV1PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh': {
      id: '/api/public/cron/refresh'
      path: '/api/public/cron/refresh'
      fullPath: '/api/public/cron/refresh'
      preLoaderRoute: typeof ApiPublicCronRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBacktestRoute: typeof AuthenticatedBacktestRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSettlementRoute: typeof AuthenticatedSettlementRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBacktestRoute: AuthenticatedBacktestRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSettlementRoute: AuthenticatedSettlementRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicCronRefreshRoute: ApiPublicCronRefreshRoute,
  ApiPublicV1PicksRoute: ApiPublicV1PicksRoute,
  ApiPublicV1PredictionsRoute: ApiPublicV1PredictionsRoute,
  ApiPublicV1SharpMovesRoute: ApiPublicV1SharpMovesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
